"""Starter repository and PyTorch skeleton generation."""

from __future__ import annotations

from .models import ArchitectureGraph, DependencyReport, GeneratedFile, PseudoCodeBlock
from .reproducibility import ReproducibilityAnalyzer
from .text import slugify


class CodeGenerationEngine:
    """Generate files for an executable paper implementation starter repo."""

    def generate(
        self,
        architecture: ArchitectureGraph,
        pseudo_code: list[PseudoCodeBlock],
        dependencies: DependencyReport,
        experiment_yaml: str,
        checklist_markdown: str,
    ) -> list[GeneratedFile]:
        return [
            GeneratedFile("README.md", self._readme(architecture, dependencies)),
            GeneratedFile("requirements.txt", self._requirements(dependencies)),
            GeneratedFile("configs/baseline_reproduction.yaml", experiment_yaml),
            GeneratedFile("src/paper_model/model.py", self._model_py(architecture)),
            GeneratedFile("src/paper_model/data.py", self._data_py(dependencies)),
            GeneratedFile("src/paper_model/procedures.py", self._procedures_py(pseudo_code)),
            GeneratedFile("scripts/train.py", self._train_py(dependencies)),
            GeneratedFile("docs/implementation_checklist.md", checklist_markdown),
            GeneratedFile("docs/reproducibility_workflow.md", ReproducibilityAnalyzer.workflow_markdown([])),
        ]

    @staticmethod
    def _readme(architecture: ArchitectureGraph, dependencies: DependencyReport) -> str:
        components = "\n".join(f"- {component.name} ({component.kind})" for component in architecture.components)
        return (
            "# Paper Implementation Starter Repo\n\n"
            "Generated by arXiv Paper Summariser V9.\n\n"
            "## Architecture\n"
            f"{components}\n\n"
            "## Dependencies\n"
            f"- Python packages: {', '.join(dependencies.python_packages)}\n"
            f"- Datasets: {', '.join(dependencies.datasets)}\n"
            f"- Hardware: {', '.join(dependencies.hardware)}\n"
        )

    @staticmethod
    def _requirements(dependencies: DependencyReport) -> str:
        packages = dependencies.python_packages
        if "torch" not in packages:
            packages = ["torch", *packages]
        return "\n".join(packages) + "\n"

    @staticmethod
    def _model_py(architecture: ArchitectureGraph) -> str:
        module_methods = []
        for component in architecture.components:
            if component.kind in {"module", "backbone", "head"}:
                class_name = "".join(part.title() for part in slugify(component.name).split("_"))
                module_methods.append(
                    f"\n\nclass {class_name}(nn.Module):\n"
                    f"    \"\"\"Skeleton for {component.name}. Evidence: {component.evidence[:120]}\"\"\"\n\n"
                    "    def __init__(self, hidden_dim: int = 128) -> None:\n"
                    "        super().__init__()\n"
                    "        self.projection = nn.LazyLinear(hidden_dim)\n\n"
                    "    def forward(self, inputs: torch.Tensor) -> torch.Tensor:\n"
                    "        return torch.relu(self.projection(inputs))\n"
                )
        if not module_methods:
            module_methods.append(
                "\n\nclass PaperBackbone(nn.Module):\n"
                "    def __init__(self, hidden_dim: int = 128) -> None:\n"
                "        super().__init__()\n"
                "        self.projection = nn.LazyLinear(hidden_dim)\n\n"
                "    def forward(self, inputs: torch.Tensor) -> torch.Tensor:\n"
                "        return torch.relu(self.projection(inputs))\n"
            )
        return (
            "from __future__ import annotations\n\n"
            "import torch\n"
            "from torch import nn\n"
            + "".join(module_methods)
            + "\n\nclass PaperModel(nn.Module):\n"
            "    \"\"\"Composable PyTorch model assembled from reconstructed components.\"\"\"\n\n"
            "    def __init__(self, input_dim: int = 128, hidden_dim: int = 128, output_dim: int = 10) -> None:\n"
            "        super().__init__()\n"
            "        self.input_layer = nn.Linear(input_dim, hidden_dim)\n"
            "        self.output_layer = nn.Linear(hidden_dim, output_dim)\n\n"
            "    def forward(self, inputs: torch.Tensor) -> torch.Tensor:\n"
            "        hidden = torch.relu(self.input_layer(inputs))\n"
            "        return self.output_layer(hidden)\n"
        )

    @staticmethod
    def _data_py(dependencies: DependencyReport) -> str:
        dataset = dependencies.datasets[0]
        return (
            "from __future__ import annotations\n\n"
            "import torch\n"
            "from torch.utils.data import DataLoader, TensorDataset\n\n\n"
            "def build_dataloader(batch_size: int = 32) -> DataLoader:\n"
            f"    \"\"\"Replace this synthetic loader with the {dataset} pipeline.\"\"\"\n"
            "    features = torch.randn(128, 128)\n"
            "    labels = torch.randint(0, 10, (128,))\n"
            "    return DataLoader(TensorDataset(features, labels), batch_size=batch_size, shuffle=True)\n"
        )

    @staticmethod
    def _procedures_py(pseudo_code: list[PseudoCodeBlock]) -> str:
        lines = ["from __future__ import annotations", "", "", "IMPLEMENTATION_STEPS = ["]
        for block in pseudo_code:
            lines.append(f"    # {block.title}")
            for step in block.steps:
                lines.append(f"    {step!r},")
        lines.extend([
            "]",
            "",
            "",
            "def describe_workflow() -> list[str]:",
            "    return list(IMPLEMENTATION_STEPS)",
            "",
        ])
        return "\n".join(lines)

    @staticmethod
    def _train_py(dependencies: DependencyReport) -> str:
        metric = dependencies.metrics[0]
        return (
            "from __future__ import annotations\n\n"
            "import argparse\n"
            "import torch\n"
            "from paper_model.data import build_dataloader\n"
            "from paper_model.model import PaperModel\n\n\n"
            "def train(epochs: int = 1, batch_size: int = 32) -> None:\n"
            "    model = PaperModel()\n"
            "    optimizer = torch.optim.Adam(model.parameters(), lr=1e-3)\n"
            "    criterion = torch.nn.CrossEntropyLoss()\n"
            "    for epoch in range(epochs):\n"
            "        for features, labels in build_dataloader(batch_size):\n"
            "            optimizer.zero_grad(set_to_none=True)\n"
            "            loss = criterion(model(features), labels)\n"
            "            loss.backward()\n"
            "            optimizer.step()\n"
            f"        print(f'epoch={{epoch}} {metric}=placeholder loss={{loss.item():.4f}}')\n\n\n"
            "if __name__ == '__main__':\n"
            "    parser = argparse.ArgumentParser()\n"
            "    parser.add_argument('--epochs', type=int, default=1)\n"
            "    parser.add_argument('--batch-size', type=int, default=32)\n"
            "    parser.add_argument('--config', default='configs/baseline_reproduction.yaml')\n"
            "    args = parser.parse_args()\n"
            "    train(epochs=args.epochs, batch_size=args.batch_size)\n"
        )
